# Checking Redundancy

In [2]:
import numpy as np

In [27]:
s1 = np.random.rand(3,5)
s2 = s1
s2 = np.delete(s2, 0, axis=0)
s2 = np.append(s2, np.random.rand(1,5), axis=0)
print(s1)
print(s2)

[[ 0.91508797  0.9648517   0.02615523  0.61465158  0.6152156 ]
 [ 0.65808767  0.04313846  0.88823323  0.50813595  0.85684183]
 [ 0.67124409  0.46073549  0.10880122  0.27033094  0.21669603]]
[[  6.58087673e-01   4.31384633e-02   8.88233233e-01   5.08135951e-01
    8.56841828e-01]
 [  6.71244094e-01   4.60735491e-01   1.08801223e-01   2.70330940e-01
    2.16696032e-01]
 [  3.87481860e-02   8.78704544e-02   6.90416620e-01   2.09204235e-04
    6.02886656e-02]]


In [28]:
n = min(s1.shape)
s1_k = np.zeros([n] + list(s1.shape))
s1_k[0] = s1
for i in range(1,s1.shape[0]):
    s1_k[i,:-i,:] = s1[i:,:] 
print(s1_k)

[[[ 0.91508797  0.9648517   0.02615523  0.61465158  0.6152156 ]
  [ 0.65808767  0.04313846  0.88823323  0.50813595  0.85684183]
  [ 0.67124409  0.46073549  0.10880122  0.27033094  0.21669603]]

 [[ 0.65808767  0.04313846  0.88823323  0.50813595  0.85684183]
  [ 0.67124409  0.46073549  0.10880122  0.27033094  0.21669603]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.67124409  0.46073549  0.10880122  0.27033094  0.21669603]
  [ 0.          0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.        ]]]


In [35]:
np.sum(s1_k == s2, axis=2)

array([[0, 0, 0],
       [5, 5, 0],
       [0, 0, 0]])

In [19]:
s1 = np.random.rand(5,5,3)
s2 = s1
s2 = np.delete(s2, 0, axis=2)
s2 = np.append(s2, np.random.rand(5,5,1), axis=2)
print(s1)
print(s2)

[[[ 0.32256437  0.17689491  0.35719715]
  [ 0.87371824  0.34160381  0.73071603]
  [ 0.94513732  0.52576831  0.03553826]
  [ 0.43225888  0.44616017  0.40875774]
  [ 0.58974116  0.77268996  0.2365597 ]]

 [[ 0.50469574  0.99144875  0.13118699]
  [ 0.35714809  0.96797927  0.69102127]
  [ 0.52279951  0.71160093  0.37392812]
  [ 0.89183821  0.33510713  0.43607929]
  [ 0.84787998  0.1549218   0.66845487]]

 [[ 0.70080123  0.82899714  0.94285021]
  [ 0.49296316  0.81123482  0.68463845]
  [ 0.03676059  0.10041627  0.33149014]
  [ 0.03492494  0.80004431  0.9952334 ]
  [ 0.76527588  0.61035169  0.4381703 ]]

 [[ 0.66157863  0.42676467  0.56492477]
  [ 0.48828764  0.93494685  0.75088877]
  [ 0.12065261  0.01046243  0.59694617]
  [ 0.30572434  0.32420119  0.19629985]
  [ 0.42834025  0.28481974  0.59615413]]

 [[ 0.15636965  0.0767195   0.22351607]
  [ 0.20290592  0.62062103  0.55014841]
  [ 0.61893622  0.33591903  0.10320199]
  [ 0.19828339  0.55554628  0.9979969 ]
  [ 0.58485483  0.93061915  0.71

This is getting too complicated. Let's try a different approach.

## Specifying overlap shape

In [40]:
s1 = np.random.rand(3,4,4)
s2 = s1
s2 = np.delete(s2, 0, axis=0)
s2 = np.append(s2, np.random.rand(1,4,4), axis=0)
print(s1)
print()
print(s2)

[[[ 0.94119315  0.18062352  0.38054649  0.42564264]
  [ 0.37331248  0.40787425  0.11785538  0.10967169]
  [ 0.90173195  0.35498705  0.6916911   0.98344993]
  [ 0.39383003  0.51895111  0.34010159  0.87591904]]

 [[ 0.05690575  0.19663351  0.55250624  0.21273953]
  [ 0.28415051  0.60671765  0.52687011  0.63351982]
  [ 0.63118038  0.00651522  0.54890456  0.51836471]
  [ 0.79023461  0.13501319  0.04713607  0.91360088]]

 [[ 0.58855098  0.27054629  0.16603246  0.11925372]
  [ 0.27516131  0.29114459  0.73639503  0.60164148]
  [ 0.94077293  0.86084528  0.46436561  0.13431836]
  [ 0.59856395  0.25912547  0.2222673   0.19892706]]]

[[[ 0.05690575  0.19663351  0.55250624  0.21273953]
  [ 0.28415051  0.60671765  0.52687011  0.63351982]
  [ 0.63118038  0.00651522  0.54890456  0.51836471]
  [ 0.79023461  0.13501319  0.04713607  0.91360088]]

 [[ 0.58855098  0.27054629  0.16603246  0.11925372]
  [ 0.27516131  0.29114459  0.73639503  0.60164148]
  [ 0.94077293  0.86084528  0.46436561  0.13431836]
  [

In [45]:
overlap_shape = [2,4,4]
s3 = np.zeros([i - j for i,j in zip(s2.shape, overlap_shape)])
print(s3.shape)

(1, 4, 4)


In [56]:
s3 = np.delete(s1, overlap_shape, axis=0)
print(s1)
print(s3.shape)
print(s3)

[[[ 0.94119315  0.18062352  0.38054649  0.42564264]
  [ 0.37331248  0.40787425  0.11785538  0.10967169]
  [ 0.90173195  0.35498705  0.6916911   0.98344993]
  [ 0.39383003  0.51895111  0.34010159  0.87591904]]

 [[ 0.05690575  0.19663351  0.55250624  0.21273953]
  [ 0.28415051  0.60671765  0.52687011  0.63351982]
  [ 0.63118038  0.00651522  0.54890456  0.51836471]
  [ 0.79023461  0.13501319  0.04713607  0.91360088]]

 [[ 0.58855098  0.27054629  0.16603246  0.11925372]
  [ 0.27516131  0.29114459  0.73639503  0.60164148]
  [ 0.94077293  0.86084528  0.46436561  0.13431836]
  [ 0.59856395  0.25912547  0.2222673   0.19892706]]]
(1, 4, 4)
[[[ 0.05690575  0.19663351  0.55250624  0.21273953]
  [ 0.28415051  0.60671765  0.52687011  0.63351982]
  [ 0.63118038  0.00651522  0.54890456  0.51836471]
  [ 0.79023461  0.13501319  0.04713607  0.91360088]]]


In [62]:
s3[[slice(None,)]*2 + [2]]

array([[ 0.55250624,  0.52687011,  0.54890456,  0.04713607]])