In [5]:
import tensorflow as tf
import numpy as np

In [33]:
a = tf.placeholder(tf.int32, shape=[None, 2])
q_s = tf.placeholder(tf.float32, shape=[None, 4])

In [34]:
q_sa = tf.gather_nd(q_s, a)
sess = tf.Session()

In [35]:
q_s_t = np.random.rand(3, 4)
a_t = [[0, 1], [1, 3], [2, 2]]
print(q_s_t)
print(a_t)
fd = {q_s: q_s_t, a: a_t}
sess.run(q_sa, feed_dict=fd)

[[ 0.35143887  0.22088295  0.78431705  0.22921055]
 [ 0.21140967  0.82402759  0.79057975  0.01022777]
 [ 0.01357729  0.51656414  0.09268521  0.03675706]]
[[0, 1], [1, 3], [2, 2]]


array([ 0.22088295,  0.01022777,  0.09268521], dtype=float32)

In [61]:
a_t = np.asarray([2, 1, 3])
fd = {q_s: q_s_t, a: a_t}
try:
    sess.run(q_sa, feed_dict=fd)
except Exception as e:
    print(e)
    a_t = np.column_stack([np.arange(a_t.shape[0]), a_t])
    fd = {q_s: q_s_t, a: a_t}
    print(a_t)
    print(sess.run(q_sa, feed_dict=fd))

Cannot feed value of shape (3,) for Tensor 'Placeholder_6:0', which has shape '(?, 2)'
[[0 2]
 [1 1]
 [2 3]]
[ 0.78431708  0.8240276   0.03675706]
